//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/NotStupid.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NotStupid : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NotStupid()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""NotStupid"",
    ""maps"": [
        {
            ""name"": ""CharacterMove"",
            ""id"": ""c5796bb9-eea3-42e9-ba6b-e54208b20ad1"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""3952c785-6827-4c07-b72d-e9b13b074eb4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""b3a82bbe-e57f-4ea8-8c03-36fcf4af0de0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FireWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""5189dcbc-321f-4dc6-bb5d-90d4f536f4b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FireSplitter"",
                    ""type"": ""Button"",
                    ""id"": ""0f2da9ec-b4be-4c99-8dc3-593085d7e4ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""cf080b6c-9049-4552-b79d-764eb87c0651"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""abb1970e-11ee-45e3-87a5-ac5fee7c7ae3"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""177e83db-d767-4a1a-883a-5670217b90ea"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d3c0dfb7-a2c1-4ede-9163-35df595235e2"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""dc57f9cd-b491-4673-8416-ce7a121505b2"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5108c401-8225-4b84-b3da-361a7f69361c"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f5fb617-fc60-4b1e-905c-02e31920b88d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FireWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cae9efe0-8556-443f-bed3-674dd3ffbdab"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FireSplitter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""TargetDummy"",
            ""id"": ""60e6c4fd-8d04-462c-bf5f-8f2fec26b411"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""e4938fc6-e393-4c09-9451-21b5612cfa08"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0ca1028f-f4ec-4157-b050-31423aa2adb7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""58308600-6add-4c8a-bf83-edf36db09400"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""64ad5649-a0a0-46f1-9245-158ea6b7814e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""dcb389ad-7eb9-46b5-bf31-e1044c97d3ea"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""18be673a-0e5b-4938-af23-37eba840219b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CharacterMove
        m_CharacterMove = asset.FindActionMap("CharacterMove", throwIfNotFound: true);
        m_CharacterMove_Move = m_CharacterMove.FindAction("Move", throwIfNotFound: true);
        m_CharacterMove_Run = m_CharacterMove.FindAction("Run", throwIfNotFound: true);
        m_CharacterMove_FireWeapon = m_CharacterMove.FindAction("FireWeapon", throwIfNotFound: true);
        m_CharacterMove_FireSplitter = m_CharacterMove.FindAction("FireSplitter", throwIfNotFound: true);
        // TargetDummy
        m_TargetDummy = asset.FindActionMap("TargetDummy", throwIfNotFound: true);
        m_TargetDummy_Move = m_TargetDummy.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CharacterMove
    private readonly InputActionMap m_CharacterMove;
    private ICharacterMoveActions m_CharacterMoveActionsCallbackInterface;
    private readonly InputAction m_CharacterMove_Move;
    private readonly InputAction m_CharacterMove_Run;
    private readonly InputAction m_CharacterMove_FireWeapon;
    private readonly InputAction m_CharacterMove_FireSplitter;
    public struct CharacterMoveActions
    {
        private @NotStupid m_Wrapper;
        public CharacterMoveActions(@NotStupid wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_CharacterMove_Move;
        public InputAction @Run => m_Wrapper.m_CharacterMove_Run;
        public InputAction @FireWeapon => m_Wrapper.m_CharacterMove_FireWeapon;
        public InputAction @FireSplitter => m_Wrapper.m_CharacterMove_FireSplitter;
        public InputActionMap Get() { return m_Wrapper.m_CharacterMove; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterMoveActions set) { return set.Get(); }
        public void SetCallbacks(ICharacterMoveActions instance)
        {
            if (m_Wrapper.m_CharacterMoveActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_CharacterMoveActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_CharacterMoveActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_CharacterMoveActionsCallbackInterface.OnMove;
                @Run.started -= m_Wrapper.m_CharacterMoveActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_CharacterMoveActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_CharacterMoveActionsCallbackInterface.OnRun;
                @FireWeapon.started -= m_Wrapper.m_CharacterMoveActionsCallbackInterface.OnFireWeapon;
                @FireWeapon.performed -= m_Wrapper.m_CharacterMoveActionsCallbackInterface.OnFireWeapon;
                @FireWeapon.canceled -= m_Wrapper.m_CharacterMoveActionsCallbackInterface.OnFireWeapon;
                @FireSplitter.started -= m_Wrapper.m_CharacterMoveActionsCallbackInterface.OnFireSplitter;
                @FireSplitter.performed -= m_Wrapper.m_CharacterMoveActionsCallbackInterface.OnFireSplitter;
                @FireSplitter.canceled -= m_Wrapper.m_CharacterMoveActionsCallbackInterface.OnFireSplitter;
            }
            m_Wrapper.m_CharacterMoveActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @FireWeapon.started += instance.OnFireWeapon;
                @FireWeapon.performed += instance.OnFireWeapon;
                @FireWeapon.canceled += instance.OnFireWeapon;
                @FireSplitter.started += instance.OnFireSplitter;
                @FireSplitter.performed += instance.OnFireSplitter;
                @FireSplitter.canceled += instance.OnFireSplitter;
            }
        }
    }
    public CharacterMoveActions @CharacterMove => new CharacterMoveActions(this);

    // TargetDummy
    private readonly InputActionMap m_TargetDummy;
    private ITargetDummyActions m_TargetDummyActionsCallbackInterface;
    private readonly InputAction m_TargetDummy_Move;
    public struct TargetDummyActions
    {
        private @NotStupid m_Wrapper;
        public TargetDummyActions(@NotStupid wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_TargetDummy_Move;
        public InputActionMap Get() { return m_Wrapper.m_TargetDummy; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TargetDummyActions set) { return set.Get(); }
        public void SetCallbacks(ITargetDummyActions instance)
        {
            if (m_Wrapper.m_TargetDummyActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_TargetDummyActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_TargetDummyActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_TargetDummyActionsCallbackInterface.OnMove;
            }
            m_Wrapper.m_TargetDummyActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
            }
        }
    }
    public TargetDummyActions @TargetDummy => new TargetDummyActions(this);
    public interface ICharacterMoveActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnFireWeapon(InputAction.CallbackContext context);
        void OnFireSplitter(InputAction.CallbackContext context);
    }
    public interface ITargetDummyActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
}
